# Generated by Django 2.0.5 on 2018-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansApp', '0003_loan_loanstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loanState',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('V', 'Vigente'), ('C', 'Caducado'), ('P', 'Perdido'), ('R', 'Recibido')], default='V', max_length=1, verbose_name='Estado Prestamo'),
        ),
    ]
