# Generated by Django 2.0.5 on 2018-08-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansApp', '0004_auto_20180811_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('E', 'En revisión'), ('V', 'Vigente'), ('C', 'Caducado'), ('P', 'Perdido'), ('R', 'Recibido')], default='E', max_length=1, verbose_name='Estado Prestamo'),
        ),
    ]
